= Allegations of sexual misconduct

Julian Assange faced allegations of sexual misconduct by two Swedish women. The case was closed during his stay in Sweden, then re-opened while he was in the U.K. (TODO Give sources). Going back to Sweden to explain his case was associated with the following risks.

	. There was a credible threat that the US wanted Julian Assange to be extradited
	. There was a credible threat that Sweden would extradite Julian Assange to the US * TODO back-up this claim*
	. Julian Assange might face important risks if transferred to the US * TODO back-up this claim*

However,

[start=4]
	. Julian Assange repeatedly offered Sweden alternative methods of questioning him, which “Sweden refused, unreasonably and disproportionately”, according to the United Nations https://en.wikipedia.org/wiki/Working_Group_on_Arbitrary_Detention[Working Group on Arbitrary Detention].

See below for details and sources.

== 1
“a Grand Jury has been convened to criminally investigate WikiLeaks and Julian Assange and determine whether an indictment against them is warranted. (…) the Grand Jury is investigating possible violations of the Espionage Act (18 U.S.C. 793), a draconian 1917 law under which no non-government-employee has ever been convicted for disclosing classified information.  The most strident anti-WikiLeaks politicians -- such as Dianne Feinstein and Newt Gingrich -- have called for the prosecution of the whistle-blowing group under this law, and it appears that the Obama DOJ [Department of Justice] is at least strongly considering that possibility.” Glenn Greenwald, https://www.salon.com/2011/04/27/wikileaks_26/[_FBI serves Grand Jury subpoena likely relating to WikiLeaks_], Salon, 27 April 2011

The Department of Justice https://www.nytimes.com/2019/04/11/world/europe/julian-assange-wikileaks-ecuador-embassy.html[unsealed] an https://www.justice.gov/opa/pr/wikileaks-founder-charged-computer-hacking-conspiracy[indictment] on the 11th of April, 2019 (the day Assange got arrested from Ecuador’s embassy in London). -- The New York Times and the U.S. Department of Justice, 11 April 2019 (see links in text)

“Does the US want Assange to be extradited? Almost certainly, but the Home Office never confirms whether an extradition request has been made or received until the person in question has been arrested. Last month, the US attorney general, Jeff Sessions, said the arrest of Assange was a “priority” after the CIA director, Mike Pompeo, described WikiLeaks as a “hostile intelligence service” and a threat to US national security.” https://www.theguardian.com/media/2017/may/19/what-has-happened-to-julian-assange-key-questions-answered[Can Julian Assange now walk free? What happens next - Q&A], The Guardian, 19 May 2017

TODO what should we do with this?
Autres éléments relatifs à l'enquête en cours par les US depuis 2011:
- Interrogatoires de Jacob Applebaum, Jason Katz, David House
- Arrestations récentes de Chelsea Manning et Ola Bini

== 3
TODO “If Mr. Assange is convicted on the conspiracy to hack offense alone, he could face up to five years in prison. The government could later seek to charge him with additional offenses, but because of extradition practices, any such superseding indictment would most likely need to come soon, before Britain formally decides whether to transfer custody of him.”, says NYT (link above). We should comment on this.

== 4
“the context of his deprivation of liberty has arisen from the failure of Sweden which initiated a process against him to obtain his extradition, in the face of contradictory wishes expressed by “complainants”, having not established a prima facie case, and refusing, unreasonably and disproportionately, to achieve a process of questioning of him, if desired, through the normal processes of mutual assistance. Further, by his offer of co-operation in facilitating a number of alternative methods short of being extradited to Sweden – where it is further stated as a matter of record, that he will then be imprisoned in Sweden on arrival and as a foreigner with no ties to Sweden, in custody until trial.” -- https://www.ohchr.org/_layouts/15/WopiFrame.aspx?sourcedoc=/Documents/Issues/Detention/A.HRC.WGAD.2015.docx&action=default&DefaultItemOpen=1[Source]: Opinions adopted by the Working Group on Arbitrary Detention at its seventy-fourth session, 30 November – 4 December 2015

“Sweden closed the preliminary investigation against Julian Assange in May 2017.
The Swedish prosecutor had been compelled to travel to London to take Mr. Assange’s testimony six months prior.” -- Source: https://justice4assange.com/Assange-Testimony.html, contient les sources et le témoignage de JA par la Suède. TODO ¿huh


