= Allegations of sexual misconduct

Julian Assange faced allegations of sexual misconduct by two Swedish women (https://www.theguardian.com/media/2010/dec/17/julian-assange-sweden[Guardian]). The case was closed during his stay in Sweden, then re-opened while he was in the U.K. Going back to Sweden to explain his case was associated with the following risks.

	. There was a credible threat that the US wanted Julian Assange to be extradited
	. There was a credible threat that Sweden would extradite Julian Assange to the US * TODO back-up this claim*
	. Julian Assange might face important risks if transferred to the US * TODO back-up this claim*

However,

[start=4]
	. Julian Assange repeatedly offered Sweden alternative methods of questioning him, which “Sweden refused, unreasonably and disproportionately”, according to the United Nations Working Group on Arbitrary Detention.
	. Sweden finally agreed to question him at the Embassy
	. Numerous signs suggest that the chief prosecutor in Sweden did not consider the accusation of rape credible.

See below for details and sources.

== 1
“a Grand Jury has been convened to criminally investigate WikiLeaks and Julian Assange and determine whether an indictment against them is warranted. (…) the Grand Jury is investigating possible violations of the Espionage Act (18 U.S.C. 793), a draconian 1917 law under which no non-government-employee has ever been convicted for disclosing classified information.  The most strident anti-WikiLeaks politicians -- such as Dianne Feinstein and Newt Gingrich -- have called for the prosecution of the whistle-blowing group under this law, and it appears that the Obama DOJ [Department of Justice] is at least strongly considering that possibility.” Glenn Greenwald, https://www.salon.com/2011/04/27/wikileaks_26/[_FBI serves Grand Jury subpoena likely relating to WikiLeaks_], Salon, 27 April 2011

The Department of Justice https://www.nytimes.com/2019/04/11/world/europe/julian-assange-wikileaks-ecuador-embassy.html[unsealed] an https://www.justice.gov/opa/pr/wikileaks-founder-charged-computer-hacking-conspiracy[indictment] on the 11th of April, 2019 (the day Assange got arrested from Ecuador’s embassy in London). -- The New York Times and the U.S. Department of Justice, 11 April 2019 (see links in text)

“Does the US want Assange to be extradited? Almost certainly, but the Home Office never confirms whether an extradition request has been made or received until the person in question has been arrested. Last month, the US attorney general, Jeff Sessions, said the arrest of Assange was a “priority” after the CIA director, Mike Pompeo, described WikiLeaks as a “hostile intelligence service” and a threat to US national security.” https://www.theguardian.com/media/2017/may/19/what-has-happened-to-julian-assange-key-questions-answered[Can Julian Assange now walk free? What happens next - Q&A], The Guardian, 19 May 2017

TODO what should we do with this?
Autres éléments relatifs à l'enquête en cours par les US depuis 2011:
- Interrogatoires de Jacob Applebaum, Jason Katz, David House
- Arrestations récentes de Chelsea Manning et Ola Bini

== 2
“lawyers argue that his extradition from Sweden would be even less likely than from the UK.” https://www.bbc.com/news/world-europe-37972528

== 3
TODO “If Mr. Assange is convicted on the conspiracy to hack offense alone, he could face up to five years in prison. The government could later seek to charge him with additional offenses, but because of extradition practices, any such superseding indictment would most likely need to come soon, before Britain formally decides whether to transfer custody of him.”, says NYT (link above). We should comment on this.

== 4
“the context of his deprivation of liberty has arisen from the failure of Sweden which initiated a process against him to obtain his extradition, in the face of contradictory wishes expressed by “complainants”, having not established a prima facie case, and refusing, unreasonably and disproportionately, to achieve a process of questioning of him, if desired, through the normal processes of mutual assistance. Further, by his offer of co-operation in facilitating a number of alternative methods short of being extradited to Sweden – where it is further stated as a matter of record, that he will then be imprisoned in Sweden on arrival and as a foreigner with no ties to Sweden, in custody until trial.” -- https://www.ohchr.org/_layouts/15/WopiFrame.aspx?sourcedoc=/Documents/Issues/Detention/A.HRC.WGAD.2015.docx&action=default&DefaultItemOpen=1[Source]: Opinions adopted by the https://en.wikipedia.org/wiki/Working_Group_on_Arbitrary_Detention[Working Group on Arbitrary Detention] at its seventy-fourth session, 30 November – 4 December 2015

“Sweden closed the preliminary investigation against Julian Assange in May 2017.
The Swedish prosecutor had been compelled to travel to London to take Mr. Assange’s testimony six months prior.” -- Source: https://justice4assange.com/Assange-Testimony.html, contient les sources et le témoignage de JA par la Suède. TODO ¿huh

== 5
“Assange questioned over Sweden 'rape' at Ecuadorean embassy

Under the agreement worked out with Ecuador, the Swedes were not allowed to question Julian Assange directly. Instead questions were to be submitted in Spanish and put to the Wikileaks founder by an Ecuadorean prosecutor. No follow-up questions were allowed.

This may explain why the Swedish prosecutor had been reluctant to question Julian Assange in London, insisting it would "lower the quality of the interview".”” -- https://www.bbc.com/news/world-europe-37972528[BBC]

== 6
On the 20 Aug. 2010, “The Swedish Prosecutor's Office issues an arrest warrant for Mr Assange based on allegations of rape and molestation.” -- BBC https://www.bbc.com/news/world-europe-11949341timeline].

But one day later, “Swedish authorities have withdrawn an arrest warrant for Wikileaks founder Julian Assange, stating that the accusation of rape against him was unfounded. (…) "I don't think there is reason to suspect that he has committed rape," the chief prosecutor, Eva Finne, said. She made no comment on the status of the molestation case, a less serious charge that would not lead to an arrest warrant.” -- https://www.theguardian.com/media/2010/aug/21/julian-assange-wikileaks-arrest-warrant-sweden[The Guardian], 21 Aug 2010

Then on 1 Sep. 2010, “Swedish Director of Prosecution Marianne Ny says she is reopening the rape investigation against Mr Assange. "Considering information available at present, my judgement is that the classification of the crime is rape."” -- BBC Timeline. “She also said that an accusation of molestation - which is not a sex offence under Swedish law - against Mr Assange should be reclassified and investigated as a case of sexual coercion and sexual molestation.” -- https://www.bbc.com/news/world-europe-11151277[BBC]

“[Ms Ny] said: "If he were to return to Sweden before the statute of limitation on this case expires in August 2020, the preliminary investigation could be resumed."
She said it was "regrettable we have not been able to carry out the investigation", and added: "We are not making any pronouncement about guilt."” -- https://www.bbc.com/news/world-europe-39973864[BBC]

“The newly-released emails show that the Swedish authorities were eager to give up the case four years before they formally abandoned proceedings in 2017 and that the CPS dissuaded them from doing so.” -- https://www.theguardian.com/media/2018/feb/11/sweden-tried-to-drop-assange-extradition-in-2013-cps-emails-show[The Guardian], 11 Feb 2018

